name: youtube_analytics
version: "1.0.0"
config-version: 2

profile: youtube_analytics

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  youtube_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
